name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2 |  tr '[:upper:]' '[:lower:]')
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            -t ghcr.io/stalbrec/$REPO_NAME:${{ github.ref_name }}-${{ matrix.arch }} \
            --push .
